# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Leastsquare <- function(X, y, bh, residual) {
    invisible(.Call(`_MDIS_Leastsquare`, X, y, bh, residual))
}

statfun1 <- function(X, y) {
    .Call(`_MDIS_statfun1`, X, y)
}

comb <- function(p) {
    .Call(`_MDIS_comb`, p)
}

MDIS <- function(X, y) {
    .Call(`_MDIS_MDIS`, X, y)
}

jcisfun <- function(X, y) {
    .Call(`_MDIS_jcisfun`, X, y)
}

JCIS <- function(at, X, y) {
    .Call(`_MDIS_JCIS`, at, X, y)
}

DIS <- function(at, X, y) {
    .Call(`_MDIS_DIS`, at, X, y)
}

proposal <- function(at, X, y, Yres) {
    .Call(`_MDIS_proposal`, at, X, y, Yres)
}

proploop <- function(S, B, beta, n, IterMax) {
    .Call(`_MDIS_proploop`, S, B, beta, n, IterMax)
}

